# Generated by Django 4.2.6 on 2024-06-16 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, verbose_name='نام و نام خوانوادگی')),
                ('phone', models.IntegerField(null=True, verbose_name='شماره تماس')),
                ('email', models.EmailField(max_length=100, verbose_name='ایمیل')),
                ('text', models.TextField(max_length=1000000, verbose_name='رزومه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کاربرها',
                'verbose_name_plural': 'کاربر ها',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, verbose_name='نام و نام خوانوادگی')),
                ('phone', models.IntegerField(null=True, verbose_name='شماره تماس')),
                ('email', models.EmailField(max_length=100, verbose_name='ایمیل')),
                ('text', models.TextField(max_length=1000000, verbose_name='پیام')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مالک')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتری ها',
            },
        ),
    ]
